version: '3.5'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=nopass052700
      - POSTGRES_DB=JobFinder
      - POSTGRES_USER=postgres
    container_name: postgres
    volumes:
      - './pgdata:/var/lib/postgresql/data'
      - './init-db:/docker-entrypoint-initdb.d' # Mount the directory with the dump file
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'

  client:
    build:
      context: ./jobs-client
      dockerfile: Dockerfile
    container_name: react-client
    ports:
      - "3000:80"
    restart: always

  app: 
    build: 
      context: ./jobs-server
      dockerfile: Dockerfile 
    container_name: nest-docker-postgres 
    environment: 
      - PORT=${PORT} 
    env_file:
      - ./jobs-server/.env
    ports: 
      - '8000:8000' 
    depends_on: 
      - db 
