version: '3.9'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'nopass052700'
      POSTGRES_DB: 'JobFinder'
      container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - backend

  jobs-server:
    build: .
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: production
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

networks:
  backend:
    driver: bridge
