export interface Job {
  id: string; // ID generated by Firestore
  isChecked?: boolean;
  contactNumber: string;
  jobPlace: string;
  jobTitle: string;
  link: string;
  placeType: string;
  posted: FirebaseFirestore.Timestamp;
  skills: string[];
  type: string;
  posterId?: string;
}
